import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Printer, ChevronDown, Stethoscope, BookOpen } from "lucide-react";
import { useState } from "react";

interface ClinicalRationaleItem {
  topic: string;
  mechanism: string;
  evidence_grade: string;
}

interface ClinicalRationaleProps {
  rationale: ClinicalRationaleItem[];
  recipeTitle: string;
}

const getGradeBadgeVariant = (grade: string): "default" | "secondary" | "outline" => {
  if (grade.includes("Grade A")) return "default";
  if (grade.includes("Grade B")) return "secondary";
  return "outline";
};

const getGradeColor = (grade: string): string => {
  if (grade.includes("Grade A")) return "bg-green-100 text-green-800 border-green-300";
  if (grade.includes("Grade B")) return "bg-blue-100 text-blue-800 border-blue-300";
  if (grade.includes("Grade C")) return "bg-amber-100 text-amber-800 border-amber-300";
  return "bg-muted text-muted-foreground";
};

const ClinicalRationale = ({ rationale, recipeTitle }: ClinicalRationaleProps) => {
  const [openItems, setOpenItems] = useState<Set<number>>(new Set([0]));

  const toggleItem = (index: number) => {
    const newOpenItems = new Set(openItems);
    if (newOpenItems.has(index)) {
      newOpenItems.delete(index);
    } else {
      newOpenItems.add(index);
    }
    setOpenItems(newOpenItems);
  };

  const handlePrint = () => {
    const printContent = `
      <html>
        <head>
          <title>Clinical Rationale - ${recipeTitle}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }
            h1 { color: #1a1a1a; border-bottom: 2px solid #e5e5e5; padding-bottom: 10px; }
            h2 { color: #374151; margin-top: 24px; }
            .topic { background: #f3f4f6; padding: 16px; border-radius: 8px; margin-bottom: 16px; border-left: 4px solid #6366f1; }
            .topic-title { font-weight: bold; font-size: 16px; margin-bottom: 8px; }
            .mechanism { font-family: 'Courier New', monospace; background: #fafafa; padding: 12px; border-radius: 4px; margin: 8px 0; font-size: 13px; line-height: 1.5; }
            .grade { display: inline-block; padding: 4px 12px; border-radius: 4px; font-size: 12px; font-weight: 600; }
            .grade-a { background: #dcfce7; color: #166534; }
            .grade-b { background: #dbeafe; color: #1e40af; }
            .grade-c { background: #fef3c7; color: #92400e; }
            .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e5e5; font-size: 12px; color: #6b7280; }
            .disclaimer { background: #fef2f2; padding: 12px; border-radius: 8px; margin-top: 16px; font-size: 12px; color: #991b1b; }
          </style>
        </head>
        <body>
          <h1>🩺 Clinical Rationale</h1>
          <p><strong>Recipe:</strong> ${recipeTitle}</p>
          <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          
          <h2>Evidence-Based Analysis</h2>
          ${rationale.map(item => `
            <div class="topic">
              <div class="topic-title">${item.topic}</div>
              <div class="mechanism">${item.mechanism}</div>
              <span class="grade ${item.evidence_grade.includes('Grade A') ? 'grade-a' : item.evidence_grade.includes('Grade B') ? 'grade-b' : 'grade-c'}">
                ${item.evidence_grade}
              </span>
            </div>
          `).join('')}
          
          <div class="disclaimer">
            <strong>⚠️ Disclaimer:</strong> This clinical rationale is provided as supportive guidance only and does not constitute medical advice. 
            Healthcare providers should use clinical judgment and consider individual patient circumstances.
          </div>
          
          <div class="footer">
            Generated by Recovery Nutrition Support Tool • Evidence based on ERAS/ESPEN guidelines
          </div>
        </body>
      </html>
    `;
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.print();
    }
  };

  if (!rationale || rationale.length === 0) {
    return null;
  }

  return (
    <Card className="border-slate-300 bg-slate-50/50">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg flex items-center gap-2">
            <Stethoscope className="w-5 h-5 text-slate-600" />
            Clinical Mechanism & Evidence
          </CardTitle>
          <Button variant="outline" size="sm" onClick={handlePrint} className="gap-2">
            <Printer className="w-4 h-4" />
            Print for Chart
          </Button>
        </div>
        <p className="text-sm text-muted-foreground">
          Evidence-based rationale for healthcare professionals
        </p>
      </CardHeader>
      <CardContent className="space-y-3">
        {rationale.map((item, index) => (
          <Collapsible 
            key={index} 
            open={openItems.has(index)}
            onOpenChange={() => toggleItem(index)}
          >
            <div className="border border-slate-200 rounded-lg bg-white overflow-hidden">
              <CollapsibleTrigger className="w-full">
                <div className="flex items-center justify-between p-4 hover:bg-slate-50 transition-colors">
                  <div className="flex items-center gap-3">
                    <BookOpen className="w-4 h-4 text-slate-500" />
                    <span className="font-medium text-sm">{item.topic}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge className={`text-xs ${getGradeColor(item.evidence_grade)}`}>
                      {item.evidence_grade}
                    </Badge>
                    <ChevronDown className={`w-4 h-4 text-slate-400 transition-transform ${openItems.has(index) ? 'rotate-180' : ''}`} />
                  </div>
                </div>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <div className="px-4 pb-4 pt-0">
                  <div className="bg-slate-100 rounded-md p-3 font-mono text-xs leading-relaxed text-slate-700">
                    {item.mechanism}
                  </div>
                </div>
              </CollapsibleContent>
            </div>
          </Collapsible>
        ))}
        
        <div className="mt-4 p-3 bg-amber-50 border border-amber-200 rounded-lg text-xs text-amber-800">
          <strong>Note:</strong> This clinical rationale is supportive guidance based on ERAS/ESPEN protocols, not medical advice.
        </div>
      </CardContent>
    </Card>
  );
};

export default ClinicalRationale;
